CREATE DATABASE EEE;
USE  EEE;

-- CREATE EMPLOYEE TABLE

CREATE TABLE EMPLOYEE
(EMPLOYEE_ID INT,
NAME VARCHAR(30),
POS_ID VARCHAR(30),
EMP_SALE INT, 
PRIMARY KEY (EMPLOYEE_ID)
);
-- INSERT VALUES IN EMPLOYEE TABLE
INSERT INTO EMPLOYEE (EMPLOYEE_ID,NAME,POS_ID,EMP_SALE)
VALUES(201,"JACKSON","P61",456),(202,"NICK","P62",267),(203,"JOFFERY","P62",324),
(204,"MISTY","P63",154),(205,"JACK","P61",532);
SELECT * FROM EMPLOYEE;

-- CREAETE INCENTIVE_DETAIL TABLE
CREATE TABLE INCENTIVE_DETAIL
(P_ID VARCHAR(30),
POSITION_NAME VARCHAR(30),
SALES_MILESTONE INT,
INCENTIVE INT,
CAP INT
-- FOREIGN KEY (P_ID) REFERENCES EMPLOYEE(POS_ID)
);
-- INSERT VALUES IN INCENTIVE_DETAIL TABLE
INSERT INTO INCENTIVE_DETAIL(P_ID,POSITION_NAME,SALES_MILESTONE,INCENTIVE,CAP)
VALUES("P61","GM",120,15000,50000),("P62","AM",85,8000,23500),("P63","SATFF",45,5000,13000);
SELECT * FROM INCENTIVE_DETAIL;
SELECT E.EMPLOYEE_ID,IF((floor(((E.EMP_SALE)/(I.SALES_MILESTONE)))*I.INCENTIVE)>(I.CAP),CAP,(floor(((E.EMP_SALE)/(I.SALES_MILESTONE)))*I.INCENTIVE)) as "INSENTIVE_MADE"
FROM EMPLOYEE E INNER JOIN INCENTIVE_DETAIL I ON E.POS_ID=I.P_ID
